# This is a basic workflow to help you get started with Actions

name: codacy-ci

on:
 push:
    branches:
      - main
 pull_request:
    branches:
      - main

jobs:
 codacy-cli:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - name: Fetch real commit SHA
        env:
         SHA_FROM_PR: ${{ github.event.pull_request.head.sha }}
        run: |
          echo "SHAD_FROM_PR is ${{ github.event.pull_request.head.sha }}"
          echo "SHAD_FROM_PR is $SHA_FROM_PR"
          echo "::set-output name=COMMIT_SHA::${{ github.event.pull_request.head.sha }}"
        id: random-color-generator
      
      - name: Checkout code
        uses: actions/checkout@master
      - name: Troubleshoot Codacy Analysis CLI
        uses: troubleshoot-codacy/codacy-analysis-cli-action@master

        with:
          tool: ESLint
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
